---
- name: Setup ZSH environment with oh-my-zsh, plugins, and dotfiles
  hosts: localhost
  gather_facts: yes
  become: yes

  vars:
    localhome: "{{ ansible_env.HOME }}"
    dotfiles_repo: "https://github.com/ahmadrezaM97/dotfiles.git"

  tasks:
    - name: Install required packages on Ubuntu
      apt:
        name:
          - zsh
          - fzf
          - stow
          - git
          - bat
        state: present
        update_cache: yes
      when: ansible_facts.os_family == "Debian"

    - name: Create .local/bin directory
      file:
        path: "{{ localhome }}/.local/bin"
        state: directory
        mode: '0755'

    - name: Create symbolic link for bat (batcat)
      file:
        src: /usr/bin/batcat
        dest: "{{ localhome }}/.local/bin/bat"
        state: link
        

    - name: Install required packages on macOS using Homebrew
      homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - zsh
        - fzf
        - stow
        - git
        - bat
      when: ansible_facts.os_family == "Darwin"
    
    - name: Install oh-my-zsh
      become: false
      shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
      args:
        creates: "{{ localhome }}/.oh-my-zsh"
        executable: /bin/bash
      environment:
        RUNZSH: "no"
        CHSH: "no"

    - name: Ensure oh-my-zsh custom plugins directory exists
      file:
        path: "{{ localhome }}/.oh-my-zsh/custom/plugins"
        state: directory
        mode: '0755'

    - name: Clone zsh-autosuggestions plugin
      git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
        dest: "{{ localhome }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        update: yes

    - name: Clone zsh-syntax-highlighting plugin
      git:
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
        dest: "{{ localhome }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        update: yes

    - name: Clone you-should-use plugin
      git:
        repo: "https://github.com/MichaelAquilina/zsh-you-should-use.git"
        dest: "{{ localhome }}/.oh-my-zsh/custom/plugins/you-should-use"
        update: yes

    - name: Clone fzf plugin
      git:
        repo: "https://github.com/unixorn/fzf-zsh-plugin.git"
        dest: "{{ localhome }}/.oh-my-zsh/custom/plugins/fzf"
        update: yes

    - name: Clone zsh-bat plugin
      git:
        repo: "https://github.com/bartholomej/zsh-bat.git"
        dest: "{{ localhome }}/.oh-my-zsh/custom/plugins/zsh-bat"
        update: yes

    - name: Clone dotfiles repository
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ localhome }}/dotfiles"
        version: main
        update: yes
      become: false

    - name: Apply zsh dotfiles using GNU stow
      command: stow -t "{{ localhome }}" zsh
      args:
        chdir: "{{ localhome }}/dotfiles"
      become: false
