---
- name: Deploy SSH key
  hosts: local
  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "~/.ssh"
        state: directory
        mode: "0700"

    - name: Deploy private key
      ansible.builtin.copy:
        content: "{{ ssh_private_key }}"
        dest: "~/.ssh/id_rsa"
        mode: "0600"

    - name: Set correct permissions for SSH private key
      ansible.builtin.file:
        path: "~/.ssh/id_rsa"
        mode: "0600"
