---
- name: Install Visual Studio Code
  hosts: all
  become: true
  tasks:
    - name: Install VS Code on Ubuntu
      when: ansible_distribution == 'Ubuntu'
      block:
        - name: Add Microsoft GPG key
          ansible.builtin.apt_key:
            url: https://packages.microsoft.com/keys/microsoft.asc
            state: present

        - name: Add VS Code repository
          ansible.builtin.apt_repository:
            repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
            state: present
            filename: vscode

        - name: Install VS Code
          ansible.builtin.apt:
            name: code
            state: present
            update_cache: true

    - name: Install VS Code on macOS
      when: ansible_distribution == 'MacOSX'
      block:
        - name: Install VS Code using Homebrew cask
          community.general.homebrew_cask:
            name: visual-studio-code
            state: present

        - name: Create symbolic link for command line usage
          ansible.builtin.file:
            src: "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
            dest: /usr/local/bin/code
            state: link
