---
- name: Install Golang on macOS and Ubuntu
  hosts: localhost
  become: true
  tasks:
    - name: Install Golang on Ubuntu
      ansible.builtin.apt:
        name: golang-go
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Golang on macOS
      community.general.homebrew:
        name: go
        state: present
      when: ansible_facts['system'] == "Darwin"
